image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  # запускаем SUT (& означает, что в фоновом режиме - не блокируем терминал для запуска тестов)
  - java -jar ./artifacts/app-order.jar &
  - chmod +x gradlew

build_script:
  - ./gradlew test --info -Dselenium.headless=true # запускаем тест, флаг --info позволяет выводить больше информации, допю флаг для headless-режима